#!/usr/bin/env bash

cli_log(){
    script_name=${0##*/}
    timestamp=$(date -u +"%Y-%m-%d%T%H:%M:%SZ")
    echo "== $script_name $timestamp $1"
}

log_conn_options(){
	echo "
    -U --user=user
    -W --password=password
    -p --port=port
       --host=host
    -n --name=name
    -c --config=path/to/config
    -h --help
"
}

parse_options(){
    configFile="$WORKDIR/sqldec.config"
    if [ -f "$configFile" ]; then
        . "$configFile"
    fi

	LONGOPTS=user:,password:,port:,name:,config:schema:,help,host:
	OPTIONS=U:W:p:n:c:s:h
	PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
	if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
    		# e.g. return value is 1
    		#  then getopt has complained about wrong arguments to stdout
    		exit 2
	fi

	eval set -- "$PARSED"

    if [ ! -z "${USERNAME:-}" ]; then U=$USERNAME; else U=-; fi 
    if [ ! -z "${PASSWORD:-}" ]; then W=$PASSWORD; else W=-; fi 
    if [ ! -z "${HOST:-}" ]; then host=$HOST; else host=-; fi 
    if [ ! -z "${PORT:-}" ]; then p=$PORT; else p=5432; fi 
    if [ ! -z "${SCHEMA:-}" ]; then s=$SCHEMA; else s="schema.sql"; fi 
    if [ ! -z "${DATABASE:-}" ]; then n=$DATABASE; else n=-; fi 
    h=n
    shifts=$((0))
    while true; do
        case "$1" in
            -U|--user)
                U="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            -W|--password)
                W="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            --host)
                host="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            -p|--port)
                p="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            -n|--name)
                n="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            -c|--config)
                c="$2"
                shifts=$((shifts+2))
                shift 2
                ;;
            -h|--help)
                h=y
                shifts=$((shifts+1))
                shift
                ;;
            --)
                shifts=$((shifts+1))
                shift
                break
                ;;
            *)
                echo "Unknown argument $2"
                exit 3
                ;;
        esac
    done
}

require_argument(){
    if [ ! -z "${0:-}" ]; 
    then 
        echo "Argument $2 required"
        exit 1 
    fi 
}