#!/usr/bin/env bash

set -o errexit -o pipefail -o noclobber -o nounset

WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

! getopt --test > /dev/null 
if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    echo 'I’m sorry, `getopt --test` failed in this environment.'
    exit 1
fi

cli_help(){
    cli_name=${0##*/}
    echo "
$cli_name
Declarative SQL Migrations
Version:

Usage: sqld [option...] [command]

Commands:
    init 	Initialize database
    create 	Create migration
    apply	Apply migration
    revert	Revert a migration

Options:
    -U --user=user
    -W --password=password
    -p --port=port
       --host=host
    -n --name=name
    -c --config=path/to/config
    -h --help
"

	exit 1
}

case "$1" in
    init)
	;;
    create)
	;;
    apply)
	;;
    revert)
	;;
    *)
	cli_help
	;;
esac
