#!/usr/bin/env bash

# 1. Retrieve latest version from DB
# 2. Apply all migrations between the current version and the specified migration (latest by default)
# 3. Update version in DB

if [ $h == y ]
then
    cli_help_apply
    exit 0
fi

# Ensure connection to DB is possible
if [ $(connect_to_db) == 0 ]
then
    echo "database $n connection established"
else
    echo "could not connect to database"
    exit 0
fi

# Retrieve current version
version=$(current_version)
if [ -z $version ];
then
	echo "empty"
else
	echo "$version"
fi

cli_help_apply(){
	echo "
Usage: sqld [options...] apply [<migration-name>]

Arguments:
	<migration-name>	Optional. Runs specific migration. By default runs all the latest migrations since the latest run.

Options:
	--count n	Run N latest migrations.
	I think the above option should be an argument like <migration-name>|<count>
"
	exit 1
}
