#!/usr/bin/env bash

# 1. Connect to DB
# 2. Generate diff as new migration-up
# 3. Apply diff to shadow db and generate diff from current schema for migrate-down


require_argument "${n:-}" "DBName"
require_parameter "${2:-}" "migration_name"

if [ $h == y ]
then
    cli_help_create
    exit 0
fi

# Ensure connection to DB is possible
if [ $(connect_to_db) == 0 ]
then
    echo "database $n connection established"
else
    echo "could not connect to database"
    exit 0
fi

# Generate migration directory
prefix=`date +'%Y%m%d%H%M%S'`
mname="${prefix}_$2"
if [ -d "$PWD/migrations/$mname" ]; 
then 
	echo "A migration with the name $mname already exists" 
	exit 1
else
	mkdir -p "$PWD/migrations/$mname"
fi

# Generate diffs
PGPASSWORD=$W psql -U $U -p $p -f "$PWD/$s" "$n-shadow" &>/dev/null
source=$(db_connection_string "$n")
shadow=$(db_connection_string "$n-shadow")

migra --unsafe $source $shadow > "$PWD/migrations/$mname/up.sql" &
echo "Up migration diff generated"
migra --unsafe $shadow $source > "$PWD/migrations/$mname/down.sql" &
echo "Down migration diff generated"


# Bring shadowdb back in line with main
PGPASSWORD=$W psql -U $U -p $p -f "$PWD/migrations/$mname/down.sql" "$n-shadow" &>/dev/null

cli_help_create(){
	echo "

Usage: sqld [options...] create <migration-name>

Arguments:
	<migration-name>	The name of the migration

Options:
"
	exit 1
}