#!/usr/bin/env bash

# 1. Connect to DB
# 2. Generate diff as new migration-up
# 3. Apply diff to shadow db and generate diff from current schema for migrate-down


cli_help_create(){
	echo "

Usage: sqld create [options...] <migration-name>

Arguments:
	<migration-name>	The name of the migration

Options:
"
	exit 1
}