#!/usr/bin/env bash

# 1. Connect to DB
# 2. Create shadow DB if not exists
# 3. Create migrations folder if not exists
# 4. Create initial schema.sql file

# Enforce required arguments
require_argument "${n:-}" "DBName"
# require_argument "${}" ""

if [ $h == y ]
then
    cli_help_init
fi

# Initialize database
# query="psql -U $U -XtAc \"SELECT 1 FROM pg_database WHERE datname='$n'\""
# echo "query: $query"
if [ "$( psql -U $U -XtAc "SELECT 1 FROM pg_database WHERE datname='$n'" )" == '1' ]
then
    echo "database $n already exists"
else
    echo "creating database"
    shell $(createdb "$n")
fi

# Initialize shadow db
if [ "$( psql -U $U -XtAc "SELECT 1 FROM pg_database WHERE datname='$n-shadow'" )" == '1' ]
then
    echo "database $n-shadow already exists"
else
    echo "creating shadow database"
    shell $(createdb "$n-shadow")
fi

# Initialize schema file
if [ ! -z "${s:-}" ];
then
    schemafilepath="$PWD/schema.sql"
else
    schemafilepath="$PWD/$s"
fi
    # Create if not exists
if [ ! -f "$schemafilepath" ]; 
then
    cat "$WORKDIR/default_schema.sql" > $schemafilepath
fi
    

# Initialize migrations directory

cli_help_init(){

	echo "

Usage: sqld init
"
	exit 0
}