#!/usr/bin/env bash

# 1. Connect to DB
# 2. Create shadow DB if not exists
# 3. Create migrations folder if not exists
# 4. Create initial schema.sql file

# Enforce required arguments
require_argument "${n:-}" "DBName"
# require_argument "${}" ""

if [ $h == y ]
then
    cli_help_init
    exit 0
fi

# Initialize database
# query="psql -U $U -XtAc \"SELECT 1 FROM pg_database WHERE datname='$n'\""
# echo "query: $query"
if [ "$( psql -U $U -XtAc "SELECT 1 FROM pg_database WHERE datname='$n'" )" == '1' ]
then
    echo "database $n already exists"
else
    echo "creating database"
    shell $(createdb "$n")
fi

# Initialize shadow db
if [ "$( psql -U $U -XtAc "SELECT 1 FROM pg_database WHERE datname='$n-shadow'" )" == '1' ]
then
    echo "database $n-shadow already exists"
else
    echo "creating shadow database"
    shell $(createdb "$n-shadow")
fi

# Initialize schema
schemaFilePath="$PWD/$s"
if [ ! -f "$schemaFilePath" ]; 
then
    cat "$WORKDIR/default_schema.sql" > $schemaFilePath
fi
PGPASSWORD=$W psql -U $U -p $p -f "$PWD/$s" "$n" &>/dev/null
PGPASSWORD=$W psql -U $U -p $p -f "$PWD/$s" "$n-shadow" &>/dev/null
prefix=$(migration_prefix)
PGPASSWORD=$W psql -U $U -p $p -XtAc "INSERT INTO sqldec.version(current_migration) VALUES('${prefix}_init');" "$n"

# Initialize migrations directory
migrationsDir="$PWD/migrations"
mkdir -p "$migrationsDir"

cli_help_init(){

	echo "

Usage: sqld init
"
	exit 0
}