#!/usr/bin/env bash

# 1. Retrieve latest version from DB
# 2. Apply all down migrations to specified migration
# 3. Update version in DB

cli_help_revert(){
	
	echo "
Usage: sqld revert [options...] [<migration-name>|<count>]

Arguments:
	<migration-name>	optional. Reverts all migrations up to and including migration-name if specified. Otherwise just reverts latest migration.
	<count>			optional. Reverts latest N migrations if specified. Default is 1.

Options:
"
	exit 1
}
